// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfkbtnhzpivlmnwkqqkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNma2J0bmh6cGl2bG1ud2txcWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTYwNjgsImV4cCI6MjA3MzY5MjA2OH0.7QkYy5SQKDTuRq1FsP11sZbh1qKgyE4ExBmkbqkj13o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});